change-template: "$TITLE (#$NUMBER)"
exclude-labels:
  - 'skip-changelog'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## Changes
  $CHANGES
  ## This release was made possible by the following contributors:
  $CONTRIBUTORS
