name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: get_version
        run: grep '^[[:blank:]]*version' setup.py | cut -d'"' -f 2

  update_release_draft:
    needs: get_version
    runs-on: ubuntu-latest
    inputs:
      version: ${{ needs.get_version.outputs.version }}
      publish: true
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
